## 文件和异常

### 从文件中读取数据

```python
file_path = '/home/fileName.txt'
with open(file_path) as file_object:
    conent = file_object.read()
    print(conent.rstrip())
```

逐行读取：

```python
file_path = '/home/fileName.txt'
with open(file_path) as file_object:
    for line in file_object:
        print(line)
```

### 写入文件

权限：'r'只读；'w'写入；'a'附加；'r+'读写

```python
filename = 'filenName.txt'
with open(file_path, 'w') as file_object:
    file_object.write("life is short,\n")
    file_object.write("I need python!\n")
```

### 异常处理

示例1：

```python
print("Give me tow numbers, and I will divide them")
print("Enter 'q' to quit")

while True:
    first_number = input("\nfirst_number:")
    if(first_number == 'q'):
        break
    second_number = input("\nsecond_number:")
    if(second_number == 'q'):
        break
    try:
        answer = int(first_number) / int(second_number)
    except ZeroDivisionError:
        print("You can't divide by 0!")
    else:
        print(answer)      
```

示例2：

```python
def count_words(filename):
    try:
        with open(filename) as f_obj:
            contents = f_obj.read()
    except FileNotFoundError:
        msg = "Sorry, the file " + filename +"do not exist"
        print(msg)
    else:
        words = conents.split()
        num_words = len(words)
        print("words count is " + str(num_words))
        
filename = "Alice.txt"
count_words(filename)
```

示例3：

```python
import logging				#Python内置的logging模块可以非常容易地记录错误信息：
def foo(s):
    return 10 / int(s)

def bar(s):
    return foo(s) * 2

def main():
    try:
        bar('0')
    except Exception as e:
        logging.Exception(e)
    finally:
        print('finally...')
```

### 抛出错误

```python
def foo(s):
    n = int(s)
    if n==0:
        raise ValueError('invalid value: %s' % s)	#抛出错误
    return 10 / n

def bar():
    try:
        foo('0')
    except ValueError as e:
        print('ValueError!')
        raise										#语句如果不带参数，就会把当前错误原样抛出

bar()
```

